kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-linstor-volume
  annotations:
    volume.beta.kubernetes.io/storage-class: example-linstor-sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
