apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: example-linstor-sc
provisioner: external/linstor
parameters:
  controllers: "192.168.10.10:8080,172.0.0.1:3366"
  autoPlace: "2"
  nodeList: "node-a node-b node-c"
  storagePool: "drbd-pool"
  filesystem: "xfs"
  encryptVolumes: "yes"
  doNotPlaceWithRegex: ".*"
  disklessStoragePool: "diskless-pool"
  fsOpts: "-b size=1024"
  mountOpts: "defaults,sync,noatime"
