apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: default-shared
provisioner: external/flex-simple
parameters:
  autoPlace: "2"
  nodeList: "node-a node-b node-c"
  doNotPlaceWithRegex: ".*"
  encryptVolumes: "yes"
